sudo: required
language: python
services:
- docker
before_install:
- echo "$TRAVIS_COMMIT"
script:
- docker build -t "$DOCKER_USER/hitman_agent" .
- docker tag "$DOCKER_USER/hitman_agent:latest" "$DOCKER_USER/hitman_agent:$(echo
  $TRAVIS_COMMIT| cut -c-10)"
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push "$DOCKER_USER/hitman_agent"
env:
  global:
  - secure: z6uB6a4oKPRnDivAHr/UTMmWqhBMfvTeM7d/vbggrD3PgvgYsAO0dApEpEp7OGdKodm0zVFcfRHvEef8KzLSeOUMgpEekwQJlpAwuCVdF6qeasU9j+9zUST/xFVGrQ6W1gYOkRPx6L9JZz00p/FLsFHHAzicuGuSR7MRHDKlMI4jWY76qombr8LV22fO7SWGZ4Xm+Hr1DBDZJV+q0Od7sB7MFpkRcP+7ysfr6XjNz+ObMdW0+kUhTaorAmCfw/uAmCTPeuaadw8XVV0mGMGrABj/Lh/namLrj6EdqVF4sW9H8Cf9o31BEd+ojPxoKvJC7uJ8S3P66j2kiR7ewJWxY0OO5iblrYENcqS90maAeifJInCnJ8doiwIMbgaLg9eOEA2eEs97vBwuKrZXTI1LY51h0doaRmw2odvzhKEr2sQAlMReZtKr2nwWZrI956zHA9NxAI7Ihy2sRRMBVXV1AkqDdtCRbSopOf3CtCIph6Yym4aIWM7e9/9Jroq/JrkRXrFiDQv55+PvzUJc+3F3N14XHc1POD7NdlPwwgzr24FjBQ5WD+0TXRtZvWk8fCT1kweKiXC+2ElMgrarIoxE0FY9Z1zqgzaXLDMQ/rvu2uCWvRYdaGYDVX3icACRi3wQb0PeKSbbn8/qcngBRddCvqJ4D+WdqaRHtMNz41w9pK8=
  - secure: 0Y7EWRGmH1NtFxCROxeEX9oAzPScdJYjhQG8e7Rz9JOZQmNv6x1uoeIqyiF1j4jZsGtBej4e0PLmA5uJQJ0oQF8RIDy5pQAFjQUVljc6zu3iHwtb2Z/bpZAElvq1sDByjNs7yoZkI9en/vVCYogUgST7JX6a31WBSpCCslifh3Yc8QaIuPAqdPuv4WNv1ZpESrcKEo0tlNII7xFcKMnGUdoU3v8chSQY23jc+RSsORDv31uOunp1nJf/gfTB40cKuVQQFc5meqZswi10fvjglXwAtOGw27DmMycEitbc5qjCX01yKX6vRTbDpGigr9GH6ATQ7Zjcql7EJuoBaoS1d7Vci6fcqv0HnVuZPJ6m6LvaaW+70VxsJB24k/Qt+ewqPdwg5Ue+uJSL4556h8/hlB8JO9oe9mxV6s0Er9MIAb9aT2h1H1JbVd+Q8Lj4Wumc3ix23jrBb0SfzNVsKrpKsnFaZm3HBEHI5Bwtm02ukoSu+7Tryxp6LAEhWV8WoTNJ0KAgkTgQ6gEECJXPZN8QvR/kIQq5OTuKH0c6TLfKz+pSS7FBwQBQbRyrm/VpdIAIr9nGEXHwxs4LWhNB+DjJyh0I1ZWnaBSw6WvyBymZHaUXIEpQTpdFr5Clcs+ZxVd/PxaZtYGe76gw9y8JF58rqOz9nrrUytEx8tA49WG7O7Y=
